### PR TITLE
hmmbuild_and_search

### PR DESCRIPTION
**Pull request by ChannyClaus**
replaces jackhmmer with hmmbuild/search

the field "jackhmmer" in the config file needs to be changed to "hmmer" and the basename of the path needs to be deleted.replaces jackhmmer with hmmbuild/search

### CODE REVIEW

**Comment by b-schubert** [comment]
This has to be extensively cleaned up:
dfd771d440a4139c3820a25bd34ff72e51cd1703  and d29f608257f382d5aed0e1bc63c123709dc97557 change every file! 

Please start from a fresh branch and transfer the actual changes from d29f608257f382d5aed0e1bc63c123709dc97557. Also both hmm and jackhammer should be supported (backwards compatibility should be preserved).

Maybe abstract the search procedure into different protocols that can be chosen in the config file.

**Comment by b-schubert** [comment]
See issue #22

**Comment by aggreen** [comment]
I agree that the pull request should be cleaned up so that we can see which
files were actually changed. Fresh branch is probably the way to go.

Regarding the design decisions, we spoke with Thomas at the beginning of
this process and came up with the following (paraphrased from our email
exchange):

------------

1) Create two functions run_hmmbuild and run_hmmsearch in align.tools.
These should follow the existing functions as closely as they can in design
and parameters; especially run_hmmsearch, since the final output will be
very similar to run_jackhmmer(). Ideally, run_hmmsearch() could nearly be
used as a drop-in replacement for run_jackhmmer() since the two are very
close siblings. Also results should be returned in the same style using
namedtuples (maybe JackhmmerResult can even be reused).

2) In evcouplings.protocol, we made a new protocol similar to jackhmmer
search. We named this hmmbuild_and_search. It gives the user the option to
either input a pre-made hmm, in which case it only runs hmmsearch, or input
an alignment, in which case it runs hmmbuild and then hmmsearch.

3) keep all the alignment-based functionality in the SIFTS.by_alignment()
method as it is, including the _identify_structures function. This was
written to be pretty much agnostic of how it gets the alignment.

Only the function find_homologs_jackhmmer) as it is called now:

ali, hits = find_homologs_jackhmmer(
    sequence_database=self.sequence_file, **kwargs
)

evolved into find_homologs_hmmer(), and this function in turn uses
jackhmmer_search() *or *hmmbuild_and_search to find the sequences. The
decision whether to run jackhmmer or hmmsearch is an additional parameter
(something like method is from {"jackhmmer", "hmmsearch"}), and that gets
automatically propagated into the find_homologs() function through kwargs,
as do the input sequence and a2m alignment from the alignment stage.

----------

If we're not happy with how that design turned out we can iterate once the
pull request is cleaned up.

Anna

**Comment by ChannyClaus** [comment]
moved to https://github.com/debbiemarkslab/EVcouplings/pull/67

**Pull request closed without merging**
